// Code generated by protoc-gen-go. DO NOT EDIT.
// source: pkg/rentalmgmt/rentalmgmt.proto

package rentalmgmt

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

//USER'S SIDE
//Create New User
type NewUser struct {
	Name                 string   `protobuf:"bytes,1,opt,name=Name,proto3" json:"Name,omitempty"`
	Email                string   `protobuf:"bytes,2,opt,name=Email,proto3" json:"Email,omitempty"`
	Phone_Number         string   `protobuf:"bytes,3,opt,name=Phone_Number,json=PhoneNumber,proto3" json:"Phone_Number,omitempty"`
	Address              string   `protobuf:"bytes,4,opt,name=Address,proto3" json:"Address,omitempty"`
	District             string   `protobuf:"bytes,5,opt,name=District,proto3" json:"District,omitempty"`
	Postal_Code          string   `protobuf:"bytes,6,opt,name=Postal_Code,json=PostalCode,proto3" json:"Postal_Code,omitempty"`
	Country              string   `protobuf:"bytes,7,opt,name=Country,proto3" json:"Country,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *NewUser) Reset()         { *m = NewUser{} }
func (m *NewUser) String() string { return proto.CompactTextString(m) }
func (*NewUser) ProtoMessage()    {}
func (*NewUser) Descriptor() ([]byte, []int) {
	return fileDescriptor_3231b20ba83710a0, []int{0}
}

func (m *NewUser) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_NewUser.Unmarshal(m, b)
}
func (m *NewUser) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_NewUser.Marshal(b, m, deterministic)
}
func (m *NewUser) XXX_Merge(src proto.Message) {
	xxx_messageInfo_NewUser.Merge(m, src)
}
func (m *NewUser) XXX_Size() int {
	return xxx_messageInfo_NewUser.Size(m)
}
func (m *NewUser) XXX_DiscardUnknown() {
	xxx_messageInfo_NewUser.DiscardUnknown(m)
}

var xxx_messageInfo_NewUser proto.InternalMessageInfo

func (m *NewUser) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *NewUser) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *NewUser) GetPhone_Number() string {
	if m != nil {
		return m.Phone_Number
	}
	return ""
}

func (m *NewUser) GetAddress() string {
	if m != nil {
		return m.Address
	}
	return ""
}

func (m *NewUser) GetDistrict() string {
	if m != nil {
		return m.District
	}
	return ""
}

func (m *NewUser) GetPostal_Code() string {
	if m != nil {
		return m.Postal_Code
	}
	return ""
}

func (m *NewUser) GetCountry() string {
	if m != nil {
		return m.Country
	}
	return ""
}

//Get the User Id
type UserId struct {
	Id                   int32    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UserId) Reset()         { *m = UserId{} }
func (m *UserId) String() string { return proto.CompactTextString(m) }
func (*UserId) ProtoMessage()    {}
func (*UserId) Descriptor() ([]byte, []int) {
	return fileDescriptor_3231b20ba83710a0, []int{1}
}

func (m *UserId) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UserId.Unmarshal(m, b)
}
func (m *UserId) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UserId.Marshal(b, m, deterministic)
}
func (m *UserId) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UserId.Merge(m, src)
}
func (m *UserId) XXX_Size() int {
	return xxx_messageInfo_UserId.Size(m)
}
func (m *UserId) XXX_DiscardUnknown() {
	xxx_messageInfo_UserId.DiscardUnknown(m)
}

var xxx_messageInfo_UserId proto.InternalMessageInfo

func (m *UserId) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

type Profile struct {
	Id                   int32    `protobuf:"varint,1,opt,name=Id,proto3" json:"Id,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=Name,proto3" json:"Name,omitempty"`
	Email                string   `protobuf:"bytes,3,opt,name=Email,proto3" json:"Email,omitempty"`
	Phone_Number         string   `protobuf:"bytes,4,opt,name=Phone_Number,json=PhoneNumber,proto3" json:"Phone_Number,omitempty"`
	Address              string   `protobuf:"bytes,5,opt,name=Address,proto3" json:"Address,omitempty"`
	District             string   `protobuf:"bytes,6,opt,name=District,proto3" json:"District,omitempty"`
	Postal_Code          string   `protobuf:"bytes,7,opt,name=Postal_Code,json=PostalCode,proto3" json:"Postal_Code,omitempty"`
	Country              string   `protobuf:"bytes,8,opt,name=Country,proto3" json:"Country,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Profile) Reset()         { *m = Profile{} }
func (m *Profile) String() string { return proto.CompactTextString(m) }
func (*Profile) ProtoMessage()    {}
func (*Profile) Descriptor() ([]byte, []int) {
	return fileDescriptor_3231b20ba83710a0, []int{2}
}

func (m *Profile) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Profile.Unmarshal(m, b)
}
func (m *Profile) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Profile.Marshal(b, m, deterministic)
}
func (m *Profile) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Profile.Merge(m, src)
}
func (m *Profile) XXX_Size() int {
	return xxx_messageInfo_Profile.Size(m)
}
func (m *Profile) XXX_DiscardUnknown() {
	xxx_messageInfo_Profile.DiscardUnknown(m)
}

var xxx_messageInfo_Profile proto.InternalMessageInfo

func (m *Profile) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *Profile) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Profile) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *Profile) GetPhone_Number() string {
	if m != nil {
		return m.Phone_Number
	}
	return ""
}

func (m *Profile) GetAddress() string {
	if m != nil {
		return m.Address
	}
	return ""
}

func (m *Profile) GetDistrict() string {
	if m != nil {
		return m.District
	}
	return ""
}

func (m *Profile) GetPostal_Code() string {
	if m != nil {
		return m.Postal_Code
	}
	return ""
}

func (m *Profile) GetCountry() string {
	if m != nil {
		return m.Country
	}
	return ""
}

type Booking struct {
	StartDate            string   `protobuf:"bytes,1,opt,name=StartDate,proto3" json:"StartDate,omitempty"`
	EndDate              string   `protobuf:"bytes,2,opt,name=EndDate,proto3" json:"EndDate,omitempty"`
	UserId               int32    `protobuf:"varint,3,opt,name=UserId,proto3" json:"UserId,omitempty"`
	ItemId               int32    `protobuf:"varint,4,opt,name=ItemId,proto3" json:"ItemId,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Booking) Reset()         { *m = Booking{} }
func (m *Booking) String() string { return proto.CompactTextString(m) }
func (*Booking) ProtoMessage()    {}
func (*Booking) Descriptor() ([]byte, []int) {
	return fileDescriptor_3231b20ba83710a0, []int{3}
}

func (m *Booking) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Booking.Unmarshal(m, b)
}
func (m *Booking) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Booking.Marshal(b, m, deterministic)
}
func (m *Booking) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Booking.Merge(m, src)
}
func (m *Booking) XXX_Size() int {
	return xxx_messageInfo_Booking.Size(m)
}
func (m *Booking) XXX_DiscardUnknown() {
	xxx_messageInfo_Booking.DiscardUnknown(m)
}

var xxx_messageInfo_Booking proto.InternalMessageInfo

func (m *Booking) GetStartDate() string {
	if m != nil {
		return m.StartDate
	}
	return ""
}

func (m *Booking) GetEndDate() string {
	if m != nil {
		return m.EndDate
	}
	return ""
}

func (m *Booking) GetUserId() int32 {
	if m != nil {
		return m.UserId
	}
	return 0
}

func (m *Booking) GetItemId() int32 {
	if m != nil {
		return m.ItemId
	}
	return 0
}

//ITEM'S SIDE
//Create New Item
type NewItem struct {
	Name                 string   `protobuf:"bytes,1,opt,name=Name,proto3" json:"Name,omitempty"`
	Description          string   `protobuf:"bytes,2,opt,name=Description,proto3" json:"Description,omitempty"`
	Category             string   `protobuf:"bytes,3,opt,name=Category,proto3" json:"Category,omitempty"`
	Available_From       string   `protobuf:"bytes,4,opt,name=Available_From,json=AvailableFrom,proto3" json:"Available_From,omitempty"`
	Available_To         string   `protobuf:"bytes,5,opt,name=Available_To,json=AvailableTo,proto3" json:"Available_To,omitempty"`
	AmountPerDay         int32    `protobuf:"varint,6,opt,name=Amount_per_day,json=AmountPerDay,proto3" json:"Amount_per_day,omitempty"`
	UserID               int32    `protobuf:"varint,7,opt,name=UserID,proto3" json:"UserID,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *NewItem) Reset()         { *m = NewItem{} }
func (m *NewItem) String() string { return proto.CompactTextString(m) }
func (*NewItem) ProtoMessage()    {}
func (*NewItem) Descriptor() ([]byte, []int) {
	return fileDescriptor_3231b20ba83710a0, []int{4}
}

func (m *NewItem) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_NewItem.Unmarshal(m, b)
}
func (m *NewItem) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_NewItem.Marshal(b, m, deterministic)
}
func (m *NewItem) XXX_Merge(src proto.Message) {
	xxx_messageInfo_NewItem.Merge(m, src)
}
func (m *NewItem) XXX_Size() int {
	return xxx_messageInfo_NewItem.Size(m)
}
func (m *NewItem) XXX_DiscardUnknown() {
	xxx_messageInfo_NewItem.DiscardUnknown(m)
}

var xxx_messageInfo_NewItem proto.InternalMessageInfo

func (m *NewItem) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *NewItem) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

func (m *NewItem) GetCategory() string {
	if m != nil {
		return m.Category
	}
	return ""
}

func (m *NewItem) GetAvailable_From() string {
	if m != nil {
		return m.Available_From
	}
	return ""
}

func (m *NewItem) GetAvailable_To() string {
	if m != nil {
		return m.Available_To
	}
	return ""
}

func (m *NewItem) GetAmountPerDay() int32 {
	if m != nil {
		return m.AmountPerDay
	}
	return 0
}

func (m *NewItem) GetUserID() int32 {
	if m != nil {
		return m.UserID
	}
	return 0
}

//Get the Item Id
type ItemId struct {
	Id                   int32    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ItemId) Reset()         { *m = ItemId{} }
func (m *ItemId) String() string { return proto.CompactTextString(m) }
func (*ItemId) ProtoMessage()    {}
func (*ItemId) Descriptor() ([]byte, []int) {
	return fileDescriptor_3231b20ba83710a0, []int{5}
}

func (m *ItemId) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ItemId.Unmarshal(m, b)
}
func (m *ItemId) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ItemId.Marshal(b, m, deterministic)
}
func (m *ItemId) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ItemId.Merge(m, src)
}
func (m *ItemId) XXX_Size() int {
	return xxx_messageInfo_ItemId.Size(m)
}
func (m *ItemId) XXX_DiscardUnknown() {
	xxx_messageInfo_ItemId.DiscardUnknown(m)
}

var xxx_messageInfo_ItemId proto.InternalMessageInfo

func (m *ItemId) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

//Get a Particular Item with all Details
type Item struct {
	ID                   int32    `protobuf:"varint,1,opt,name=ID,proto3" json:"ID,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=Name,proto3" json:"Name,omitempty"`
	Description          string   `protobuf:"bytes,3,opt,name=Description,proto3" json:"Description,omitempty"`
	Category             string   `protobuf:"bytes,4,opt,name=Category,proto3" json:"Category,omitempty"`
	Available_From       string   `protobuf:"bytes,5,opt,name=Available_From,json=AvailableFrom,proto3" json:"Available_From,omitempty"`
	Available_To         string   `protobuf:"bytes,6,opt,name=Available_To,json=AvailableTo,proto3" json:"Available_To,omitempty"`
	AmountPerDay         int32    `protobuf:"varint,7,opt,name=Amount_per_day,json=AmountPerDay,proto3" json:"Amount_per_day,omitempty"`
	UserID               int32    `protobuf:"varint,8,opt,name=UserID,proto3" json:"UserID,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Item) Reset()         { *m = Item{} }
func (m *Item) String() string { return proto.CompactTextString(m) }
func (*Item) ProtoMessage()    {}
func (*Item) Descriptor() ([]byte, []int) {
	return fileDescriptor_3231b20ba83710a0, []int{6}
}

func (m *Item) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Item.Unmarshal(m, b)
}
func (m *Item) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Item.Marshal(b, m, deterministic)
}
func (m *Item) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Item.Merge(m, src)
}
func (m *Item) XXX_Size() int {
	return xxx_messageInfo_Item.Size(m)
}
func (m *Item) XXX_DiscardUnknown() {
	xxx_messageInfo_Item.DiscardUnknown(m)
}

var xxx_messageInfo_Item proto.InternalMessageInfo

func (m *Item) GetID() int32 {
	if m != nil {
		return m.ID
	}
	return 0
}

func (m *Item) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Item) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

func (m *Item) GetCategory() string {
	if m != nil {
		return m.Category
	}
	return ""
}

func (m *Item) GetAvailable_From() string {
	if m != nil {
		return m.Available_From
	}
	return ""
}

func (m *Item) GetAvailable_To() string {
	if m != nil {
		return m.Available_To
	}
	return ""
}

func (m *Item) GetAmountPerDay() int32 {
	if m != nil {
		return m.AmountPerDay
	}
	return 0
}

func (m *Item) GetUserID() int32 {
	if m != nil {
		return m.UserID
	}
	return 0
}

//To Show the Available Dates
type AvailableDates struct {
	Available_From       string   `protobuf:"bytes,1,opt,name=Available_From,json=AvailableFrom,proto3" json:"Available_From,omitempty"`
	Available_To         string   `protobuf:"bytes,2,opt,name=Available_To,json=AvailableTo,proto3" json:"Available_To,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AvailableDates) Reset()         { *m = AvailableDates{} }
func (m *AvailableDates) String() string { return proto.CompactTextString(m) }
func (*AvailableDates) ProtoMessage()    {}
func (*AvailableDates) Descriptor() ([]byte, []int) {
	return fileDescriptor_3231b20ba83710a0, []int{7}
}

func (m *AvailableDates) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AvailableDates.Unmarshal(m, b)
}
func (m *AvailableDates) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AvailableDates.Marshal(b, m, deterministic)
}
func (m *AvailableDates) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AvailableDates.Merge(m, src)
}
func (m *AvailableDates) XXX_Size() int {
	return xxx_messageInfo_AvailableDates.Size(m)
}
func (m *AvailableDates) XXX_DiscardUnknown() {
	xxx_messageInfo_AvailableDates.DiscardUnknown(m)
}

var xxx_messageInfo_AvailableDates proto.InternalMessageInfo

func (m *AvailableDates) GetAvailable_From() string {
	if m != nil {
		return m.Available_From
	}
	return ""
}

func (m *AvailableDates) GetAvailable_To() string {
	if m != nil {
		return m.Available_To
	}
	return ""
}

//For Listing all the Items
type Items struct {
	Items                []*Item  `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Items) Reset()         { *m = Items{} }
func (m *Items) String() string { return proto.CompactTextString(m) }
func (*Items) ProtoMessage()    {}
func (*Items) Descriptor() ([]byte, []int) {
	return fileDescriptor_3231b20ba83710a0, []int{8}
}

func (m *Items) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Items.Unmarshal(m, b)
}
func (m *Items) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Items.Marshal(b, m, deterministic)
}
func (m *Items) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Items.Merge(m, src)
}
func (m *Items) XXX_Size() int {
	return xxx_messageInfo_Items.Size(m)
}
func (m *Items) XXX_DiscardUnknown() {
	xxx_messageInfo_Items.DiscardUnknown(m)
}

var xxx_messageInfo_Items proto.InternalMessageInfo

func (m *Items) GetItems() []*Item {
	if m != nil {
		return m.Items
	}
	return nil
}

//REQUEST AND RESPONSE
//For Requesting
type Request struct {
	Request              string   `protobuf:"bytes,1,opt,name=request,proto3" json:"request,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Request) Reset()         { *m = Request{} }
func (m *Request) String() string { return proto.CompactTextString(m) }
func (*Request) ProtoMessage()    {}
func (*Request) Descriptor() ([]byte, []int) {
	return fileDescriptor_3231b20ba83710a0, []int{9}
}

func (m *Request) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Request.Unmarshal(m, b)
}
func (m *Request) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Request.Marshal(b, m, deterministic)
}
func (m *Request) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Request.Merge(m, src)
}
func (m *Request) XXX_Size() int {
	return xxx_messageInfo_Request.Size(m)
}
func (m *Request) XXX_DiscardUnknown() {
	xxx_messageInfo_Request.DiscardUnknown(m)
}

var xxx_messageInfo_Request proto.InternalMessageInfo

func (m *Request) GetRequest() string {
	if m != nil {
		return m.Request
	}
	return ""
}

//To Conform Item is booked
type BookingId struct {
	Id                   int32    `protobuf:"varint,1,opt,name=Id,proto3" json:"Id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *BookingId) Reset()         { *m = BookingId{} }
func (m *BookingId) String() string { return proto.CompactTextString(m) }
func (*BookingId) ProtoMessage()    {}
func (*BookingId) Descriptor() ([]byte, []int) {
	return fileDescriptor_3231b20ba83710a0, []int{10}
}

func (m *BookingId) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BookingId.Unmarshal(m, b)
}
func (m *BookingId) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BookingId.Marshal(b, m, deterministic)
}
func (m *BookingId) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BookingId.Merge(m, src)
}
func (m *BookingId) XXX_Size() int {
	return xxx_messageInfo_BookingId.Size(m)
}
func (m *BookingId) XXX_DiscardUnknown() {
	xxx_messageInfo_BookingId.DiscardUnknown(m)
}

var xxx_messageInfo_BookingId proto.InternalMessageInfo

func (m *BookingId) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

//To Show the Booked Items
type BookedItems struct {
	Id                   int32    `protobuf:"varint,1,opt,name=Id,proto3" json:"Id,omitempty"`
	ItemName             string   `protobuf:"bytes,2,opt,name=ItemName,proto3" json:"ItemName,omitempty"`
	StartDate            string   `protobuf:"bytes,3,opt,name=StartDate,proto3" json:"StartDate,omitempty"`
	EndDate              string   `protobuf:"bytes,4,opt,name=EndDate,proto3" json:"EndDate,omitempty"`
	TotalAmount          int32    `protobuf:"varint,5,opt,name=TotalAmount,proto3" json:"TotalAmount,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *BookedItems) Reset()         { *m = BookedItems{} }
func (m *BookedItems) String() string { return proto.CompactTextString(m) }
func (*BookedItems) ProtoMessage()    {}
func (*BookedItems) Descriptor() ([]byte, []int) {
	return fileDescriptor_3231b20ba83710a0, []int{11}
}

func (m *BookedItems) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BookedItems.Unmarshal(m, b)
}
func (m *BookedItems) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BookedItems.Marshal(b, m, deterministic)
}
func (m *BookedItems) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BookedItems.Merge(m, src)
}
func (m *BookedItems) XXX_Size() int {
	return xxx_messageInfo_BookedItems.Size(m)
}
func (m *BookedItems) XXX_DiscardUnknown() {
	xxx_messageInfo_BookedItems.DiscardUnknown(m)
}

var xxx_messageInfo_BookedItems proto.InternalMessageInfo

func (m *BookedItems) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *BookedItems) GetItemName() string {
	if m != nil {
		return m.ItemName
	}
	return ""
}

func (m *BookedItems) GetStartDate() string {
	if m != nil {
		return m.StartDate
	}
	return ""
}

func (m *BookedItems) GetEndDate() string {
	if m != nil {
		return m.EndDate
	}
	return ""
}

func (m *BookedItems) GetTotalAmount() int32 {
	if m != nil {
		return m.TotalAmount
	}
	return 0
}

//REVIEWS RELATED
type NewReview struct {
	Comment              string   `protobuf:"bytes,1,opt,name=Comment,proto3" json:"Comment,omitempty"`
	Rating               int32    `protobuf:"varint,2,opt,name=Rating,proto3" json:"Rating,omitempty"`
	UserId               int32    `protobuf:"varint,3,opt,name=UserId,proto3" json:"UserId,omitempty"`
	ItemId               int32    `protobuf:"varint,4,opt,name=ItemId,proto3" json:"ItemId,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *NewReview) Reset()         { *m = NewReview{} }
func (m *NewReview) String() string { return proto.CompactTextString(m) }
func (*NewReview) ProtoMessage()    {}
func (*NewReview) Descriptor() ([]byte, []int) {
	return fileDescriptor_3231b20ba83710a0, []int{12}
}

func (m *NewReview) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_NewReview.Unmarshal(m, b)
}
func (m *NewReview) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_NewReview.Marshal(b, m, deterministic)
}
func (m *NewReview) XXX_Merge(src proto.Message) {
	xxx_messageInfo_NewReview.Merge(m, src)
}
func (m *NewReview) XXX_Size() int {
	return xxx_messageInfo_NewReview.Size(m)
}
func (m *NewReview) XXX_DiscardUnknown() {
	xxx_messageInfo_NewReview.DiscardUnknown(m)
}

var xxx_messageInfo_NewReview proto.InternalMessageInfo

func (m *NewReview) GetComment() string {
	if m != nil {
		return m.Comment
	}
	return ""
}

func (m *NewReview) GetRating() int32 {
	if m != nil {
		return m.Rating
	}
	return 0
}

func (m *NewReview) GetUserId() int32 {
	if m != nil {
		return m.UserId
	}
	return 0
}

func (m *NewReview) GetItemId() int32 {
	if m != nil {
		return m.ItemId
	}
	return 0
}

type ReviewId struct {
	Id                   int32    `protobuf:"varint,1,opt,name=Id,proto3" json:"Id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ReviewId) Reset()         { *m = ReviewId{} }
func (m *ReviewId) String() string { return proto.CompactTextString(m) }
func (*ReviewId) ProtoMessage()    {}
func (*ReviewId) Descriptor() ([]byte, []int) {
	return fileDescriptor_3231b20ba83710a0, []int{13}
}

func (m *ReviewId) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReviewId.Unmarshal(m, b)
}
func (m *ReviewId) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReviewId.Marshal(b, m, deterministic)
}
func (m *ReviewId) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReviewId.Merge(m, src)
}
func (m *ReviewId) XXX_Size() int {
	return xxx_messageInfo_ReviewId.Size(m)
}
func (m *ReviewId) XXX_DiscardUnknown() {
	xxx_messageInfo_ReviewId.DiscardUnknown(m)
}

var xxx_messageInfo_ReviewId proto.InternalMessageInfo

func (m *ReviewId) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

type Review struct {
	Id                   int32    `protobuf:"varint,1,opt,name=Id,proto3" json:"Id,omitempty"`
	Comment              string   `protobuf:"bytes,2,opt,name=Comment,proto3" json:"Comment,omitempty"`
	Rating               int32    `protobuf:"varint,3,opt,name=Rating,proto3" json:"Rating,omitempty"`
	UserId               int32    `protobuf:"varint,4,opt,name=UserId,proto3" json:"UserId,omitempty"`
	ItemId               int32    `protobuf:"varint,5,opt,name=ItemId,proto3" json:"ItemId,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Review) Reset()         { *m = Review{} }
func (m *Review) String() string { return proto.CompactTextString(m) }
func (*Review) ProtoMessage()    {}
func (*Review) Descriptor() ([]byte, []int) {
	return fileDescriptor_3231b20ba83710a0, []int{14}
}

func (m *Review) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Review.Unmarshal(m, b)
}
func (m *Review) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Review.Marshal(b, m, deterministic)
}
func (m *Review) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Review.Merge(m, src)
}
func (m *Review) XXX_Size() int {
	return xxx_messageInfo_Review.Size(m)
}
func (m *Review) XXX_DiscardUnknown() {
	xxx_messageInfo_Review.DiscardUnknown(m)
}

var xxx_messageInfo_Review proto.InternalMessageInfo

func (m *Review) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *Review) GetComment() string {
	if m != nil {
		return m.Comment
	}
	return ""
}

func (m *Review) GetRating() int32 {
	if m != nil {
		return m.Rating
	}
	return 0
}

func (m *Review) GetUserId() int32 {
	if m != nil {
		return m.UserId
	}
	return 0
}

func (m *Review) GetItemId() int32 {
	if m != nil {
		return m.ItemId
	}
	return 0
}

func init() {
	proto.RegisterType((*NewUser)(nil), "rentalmgmt.NewUser")
	proto.RegisterType((*UserId)(nil), "rentalmgmt.UserId")
	proto.RegisterType((*Profile)(nil), "rentalmgmt.Profile")
	proto.RegisterType((*Booking)(nil), "rentalmgmt.Booking")
	proto.RegisterType((*NewItem)(nil), "rentalmgmt.NewItem")
	proto.RegisterType((*ItemId)(nil), "rentalmgmt.ItemId")
	proto.RegisterType((*Item)(nil), "rentalmgmt.Item")
	proto.RegisterType((*AvailableDates)(nil), "rentalmgmt.AvailableDates")
	proto.RegisterType((*Items)(nil), "rentalmgmt.Items")
	proto.RegisterType((*Request)(nil), "rentalmgmt.Request")
	proto.RegisterType((*BookingId)(nil), "rentalmgmt.BookingId")
	proto.RegisterType((*BookedItems)(nil), "rentalmgmt.BookedItems")
	proto.RegisterType((*NewReview)(nil), "rentalmgmt.NewReview")
	proto.RegisterType((*ReviewId)(nil), "rentalmgmt.ReviewId")
	proto.RegisterType((*Review)(nil), "rentalmgmt.Review")
}

func init() { proto.RegisterFile("pkg/rentalmgmt/rentalmgmt.proto", fileDescriptor_3231b20ba83710a0) }

var fileDescriptor_3231b20ba83710a0 = []byte{
	// 872 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x94, 0x56, 0xdd, 0x6e, 0xe3, 0x44,
	0x14, 0xae, 0x93, 0x38, 0x4e, 0x8e, 0xbb, 0x15, 0x0c, 0xbb, 0x8b, 0xe5, 0x82, 0xb6, 0x98, 0x1f,
	0xed, 0x55, 0x8b, 0x16, 0x10, 0x68, 0x41, 0x48, 0x69, 0xdd, 0xad, 0x22, 0xa1, 0x28, 0x32, 0xdd,
	0x9b, 0xbd, 0xb1, 0xa6, 0xf5, 0x21, 0x8c, 0xd6, 0x3f, 0xd9, 0xf1, 0xa4, 0x55, 0x78, 0x0d, 0x1e,
	0x8a, 0x47, 0xe0, 0x01, 0x10, 0xf7, 0x3c, 0x02, 0x9a, 0x1f, 0x3b, 0x4e, 0xe2, 0x84, 0x72, 0xe7,
	0xf3, 0x9d, 0x39, 0x9e, 0xf3, 0x7d, 0xe7, 0x3b, 0x71, 0xe0, 0xd9, 0xfc, 0xed, 0xec, 0x8c, 0x63,
	0x2e, 0x68, 0x9a, 0xcd, 0x32, 0xd1, 0x78, 0x3c, 0x9d, 0xf3, 0x42, 0x14, 0x04, 0x56, 0x48, 0xf0,
	0x87, 0x05, 0xce, 0x04, 0xef, 0x5f, 0x97, 0xc8, 0x09, 0x81, 0xde, 0x84, 0x66, 0xe8, 0x59, 0x27,
	0xd6, 0xf3, 0x61, 0xa4, 0x9e, 0xc9, 0x63, 0xb0, 0x2f, 0x33, 0xca, 0x52, 0xaf, 0xa3, 0x40, 0x1d,
	0x90, 0x4f, 0xe0, 0x70, 0xfa, 0x6b, 0x91, 0x63, 0x3c, 0x59, 0x64, 0x37, 0xc8, 0xbd, 0xae, 0x4a,
	0xba, 0x0a, 0xd3, 0x10, 0xf1, 0xc0, 0x19, 0x25, 0x09, 0xc7, 0xb2, 0xf4, 0x7a, 0x2a, 0x5b, 0x85,
	0xc4, 0x87, 0x41, 0xc8, 0x4a, 0xc1, 0xd9, 0xad, 0xf0, 0x6c, 0x95, 0xaa, 0x63, 0xf2, 0x0c, 0xdc,
	0x69, 0x51, 0x0a, 0x9a, 0xc6, 0x17, 0x45, 0x82, 0x5e, 0x5f, 0xa5, 0x41, 0x43, 0x12, 0x91, 0xaf,
	0xbd, 0x28, 0x16, 0xb9, 0xe0, 0x4b, 0xcf, 0xd1, 0xaf, 0x35, 0x61, 0xe0, 0x41, 0x5f, 0xb2, 0x18,
	0x27, 0xe4, 0x08, 0x3a, 0x2c, 0x51, 0x2c, 0xec, 0xa8, 0xc3, 0x92, 0xe0, 0x4f, 0x0b, 0x9c, 0x29,
	0x2f, 0x7e, 0x61, 0x29, 0xca, 0xdc, 0xb8, 0xce, 0x8d, 0x93, 0x9a, 0x73, 0xa7, 0x8d, 0x73, 0x77,
	0x1f, 0xe7, 0xde, 0x5e, 0xce, 0xf6, 0x6e, 0xce, 0xfd, 0xfd, 0x9c, 0x9d, 0x7d, 0x9c, 0x07, 0xeb,
	0x9c, 0xdf, 0x81, 0x73, 0x5e, 0x14, 0x6f, 0x59, 0x3e, 0x23, 0x1f, 0xc1, 0xf0, 0x67, 0x41, 0xb9,
	0x08, 0xa9, 0xa8, 0x26, 0xb8, 0x02, 0xe4, 0x2b, 0x2e, 0xf3, 0x44, 0xe5, 0x34, 0xd3, 0x2a, 0x24,
	0x4f, 0x2b, 0xd9, 0x14, 0x5b, 0x3b, 0xaa, 0x44, 0x7c, 0x0a, 0xfd, 0xb1, 0xc0, 0x6c, 0x9c, 0x28,
	0xa2, 0x76, 0x64, 0xa2, 0xe0, 0x2f, 0x6d, 0x18, 0x19, 0xb5, 0x1a, 0xe6, 0x04, 0xdc, 0x10, 0xcb,
	0x5b, 0xce, 0xe6, 0x82, 0x15, 0xb9, 0xb9, 0xad, 0x09, 0x49, 0x2d, 0x2e, 0xa8, 0xc0, 0x59, 0xc1,
	0x97, 0x46, 0xe1, 0x3a, 0x26, 0x9f, 0xc3, 0xd1, 0xe8, 0x8e, 0xb2, 0x94, 0xde, 0xa4, 0x18, 0xbf,
	0xe2, 0x45, 0x66, 0x64, 0x7e, 0x54, 0xa3, 0x12, 0x94, 0xb3, 0x58, 0x1d, 0xbb, 0x2e, 0x8c, 0xda,
	0x6e, 0x8d, 0x5d, 0x17, 0xe4, 0x33, 0x38, 0x1a, 0x65, 0x52, 0xa6, 0x78, 0x8e, 0x3c, 0x4e, 0xe8,
	0x52, 0xe9, 0x6e, 0x47, 0x87, 0x1a, 0x9d, 0x22, 0x0f, 0xe9, 0xb2, 0x66, 0x1f, 0x2a, 0xd9, 0x2b,
	0xf6, 0xa1, 0x34, 0x93, 0xe6, 0xbb, 0x65, 0xa6, 0x7f, 0x2c, 0xe8, 0x29, 0xf2, 0xd2, 0x49, 0x61,
	0xed, 0xa4, 0xb0, 0xd5, 0x49, 0x1b, 0x62, 0x74, 0xf7, 0x8b, 0xd1, 0xfb, 0x4f, 0x31, 0xec, 0x87,
	0x88, 0xd1, 0x7f, 0x88, 0x18, 0xce, 0x5e, 0x31, 0x06, 0x6b, 0x62, 0xbc, 0x69, 0xf4, 0x21, 0x3d,
	0x53, 0xb6, 0x74, 0x66, 0x3d, 0xa4, 0xb3, 0xce, 0x56, 0x67, 0xc1, 0x19, 0xd8, 0x52, 0xcd, 0x92,
	0x7c, 0x01, 0x36, 0x93, 0x0f, 0x9e, 0x75, 0xd2, 0x7d, 0xee, 0xbe, 0x78, 0xef, 0xb4, 0xf1, 0xb3,
	0x25, 0x4f, 0x44, 0x3a, 0x1d, 0x7c, 0x0a, 0x4e, 0x84, 0xef, 0x16, 0x58, 0x0a, 0x69, 0x6a, 0xae,
	0x1f, 0xcd, 0xf5, 0x55, 0x18, 0x1c, 0xc3, 0xd0, 0xec, 0x85, 0x9e, 0x60, 0x73, 0xe5, 0x83, 0xdf,
	0x2d, 0x70, 0x65, 0x16, 0x13, 0x7d, 0xf3, 0xe6, 0x4f, 0x82, 0x0f, 0x03, 0x99, 0x68, 0x0c, 0xb3,
	0x8e, 0xd7, 0xb7, 0xac, 0xbb, 0x67, 0xcb, 0x7a, 0xeb, 0x5b, 0x76, 0x02, 0xee, 0x75, 0x21, 0x68,
	0xaa, 0xf5, 0x56, 0x73, 0xb4, 0xa3, 0x26, 0x14, 0x64, 0x30, 0x9c, 0xe0, 0x7d, 0x84, 0x77, 0x0c,
	0xef, 0xf5, 0xc6, 0x67, 0x19, 0xe6, 0x35, 0x33, 0x13, 0xca, 0x19, 0x45, 0x54, 0xb0, 0x7c, 0xa6,
	0x5a, 0xb3, 0x23, 0x13, 0xfd, 0xef, 0x35, 0xf6, 0x61, 0xa0, 0xef, 0x6a, 0x11, 0xe8, 0x37, 0xe8,
	0x9b, 0x3e, 0x36, 0xa5, 0x69, 0xf4, 0xd5, 0xd9, 0xd5, 0x57, 0x77, 0x47, 0x5f, 0xbd, 0x1d, 0x7d,
	0xd9, 0xcd, 0xbe, 0x5e, 0xfc, 0x6d, 0xc3, 0x71, 0xa4, 0x26, 0x1f, 0x5f, 0xd2, 0x72, 0x19, 0xbf,
	0x5a, 0xe4, 0xb7, 0x72, 0x51, 0x68, 0xca, 0x04, 0xc3, 0x92, 0x7c, 0x0b, 0x70, 0xc1, 0x91, 0x0a,
	0x54, 0x5f, 0xac, 0x0f, 0x9a, 0x2e, 0x31, 0x9f, 0x31, 0x9f, 0x34, 0x41, 0x7d, 0x5d, 0x70, 0xb0,
	0x2a, 0x54, 0xcb, 0xbb, 0x59, 0x28, 0xc1, 0xf5, 0x42, 0xa3, 0x93, 0x2c, 0x74, 0xaf, 0x50, 0x8c,
	0xd2, 0x54, 0xbb, 0x65, 0xad, 0xd2, 0x38, 0xd1, 0x7f, 0x7f, 0xb3, 0xb2, 0x0c, 0x0e, 0xc8, 0x37,
	0xaa, 0x50, 0x46, 0xe7, 0x4b, 0xf9, 0xa5, 0xd9, 0x7e, 0xbb, 0xbf, 0xe5, 0xf2, 0xe0, 0x80, 0x7c,
	0x0d, 0xf0, 0x7a, 0x9e, 0x54, 0x8d, 0x6e, 0x9d, 0xd8, 0xd1, 0xe5, 0x8f, 0x40, 0xae, 0x50, 0x48,
	0xb6, 0x3f, 0x21, 0x2d, 0x2b, 0x6b, 0xb7, 0x48, 0xd1, 0x76, 0xe7, 0x97, 0x16, 0xf9, 0x0e, 0x06,
	0x72, 0x27, 0xb6, 0xc5, 0x31, 0x7b, 0xe4, 0x3f, 0x69, 0x01, 0xd5, 0xcd, 0x23, 0x38, 0xba, 0x42,
	0xd1, 0x5c, 0xa8, 0xb6, 0x5b, 0x3f, 0xdc, 0x2c, 0x37, 0x87, 0xd5, 0xe5, 0x2f, 0x61, 0x38, 0x4a,
	0x12, 0xe3, 0xb9, 0x27, 0x1b, 0xa3, 0xd1, 0xb0, 0xff, 0x78, 0x5d, 0x77, 0x6d, 0xdd, 0xe0, 0x80,
	0xbc, 0x84, 0x43, 0x2d, 0x97, 0x29, 0x27, 0xdb, 0xe7, 0x76, 0xd6, 0xfe, 0x00, 0x87, 0x21, 0xa6,
	0x58, 0xd7, 0xb6, 0x9e, 0xdb, 0x59, 0xfd, 0x3d, 0x3c, 0xd2, 0xc6, 0xd0, 0x58, 0xd9, 0x3a, 0xe1,
	0x96, 0x76, 0x24, 0xe5, 0xf3, 0x8f, 0xdf, 0x1c, 0xeb, 0x44, 0x8c, 0xb4, 0x5c, 0x9e, 0xb2, 0xfc,
	0x2c, 0x6b, 0xfc, 0x51, 0xbb, 0xe9, 0xab, 0x7f, 0x6a, 0x5f, 0xfd, 0x1b, 0x00, 0x00, 0xff, 0xff,
	0xd0, 0xe6, 0x4f, 0xda, 0xcc, 0x09, 0x00, 0x00,
}
