// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.6.1
// source: pkg/rentalmgmt/rentalmgmt.proto

package rentalmgmt

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// Rental_Easy_FunctionalitiesClient is the client API for Rental_Easy_Functionalities service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type Rental_Easy_FunctionalitiesClient interface {
	CreateUser(ctx context.Context, in *User, opts ...grpc.CallOption) (*User, error)
	GetUser(ctx context.Context, in *User, opts ...grpc.CallOption) (*User, error)
	UpdateUser(ctx context.Context, in *User, opts ...grpc.CallOption) (*User, error)
	CreateItem(ctx context.Context, in *Item, opts ...grpc.CallOption) (*Item, error)
	GetAllItems(ctx context.Context, in *ItemRequest, opts ...grpc.CallOption) (Rental_Easy_Functionalities_GetAllItemsClient, error)
	GetItemById(ctx context.Context, in *Item, opts ...grpc.CallOption) (*Item, error)
	UpdateItem(ctx context.Context, in *Item, opts ...grpc.CallOption) (*Item, error)
	DeleteItem(ctx context.Context, in *Item, opts ...grpc.CallOption) (*Item, error)
	GetUserLeasedItems(ctx context.Context, in *User, opts ...grpc.CallOption) (Rental_Easy_Functionalities_GetUserLeasedItemsClient, error)
	BookItem(ctx context.Context, in *Booking, opts ...grpc.CallOption) (*Booking, error)
	GetUserBookedItems(ctx context.Context, in *User, opts ...grpc.CallOption) (Rental_Easy_Functionalities_GetUserBookedItemsClient, error)
	AddReview(ctx context.Context, in *Review, opts ...grpc.CallOption) (*Review, error)
	UpdateReview(ctx context.Context, in *Review, opts ...grpc.CallOption) (*Review, error)
	DeleteReview(ctx context.Context, in *Review, opts ...grpc.CallOption) (*Review, error)
	GetAllReviews(ctx context.Context, in *Item, opts ...grpc.CallOption) (Rental_Easy_Functionalities_GetAllReviewsClient, error)
	SearchItems(ctx context.Context, in *ItemRequest, opts ...grpc.CallOption) (Rental_Easy_Functionalities_SearchItemsClient, error)
}

type rental_Easy_FunctionalitiesClient struct {
	cc grpc.ClientConnInterface
}

func NewRental_Easy_FunctionalitiesClient(cc grpc.ClientConnInterface) Rental_Easy_FunctionalitiesClient {
	return &rental_Easy_FunctionalitiesClient{cc}
}

func (c *rental_Easy_FunctionalitiesClient) CreateUser(ctx context.Context, in *User, opts ...grpc.CallOption) (*User, error) {
	out := new(User)
	err := c.cc.Invoke(ctx, "/rentalmgmt.Rental_Easy_Functionalities/CreateUser", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *rental_Easy_FunctionalitiesClient) GetUser(ctx context.Context, in *User, opts ...grpc.CallOption) (*User, error) {
	out := new(User)
	err := c.cc.Invoke(ctx, "/rentalmgmt.Rental_Easy_Functionalities/GetUser", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *rental_Easy_FunctionalitiesClient) UpdateUser(ctx context.Context, in *User, opts ...grpc.CallOption) (*User, error) {
	out := new(User)
	err := c.cc.Invoke(ctx, "/rentalmgmt.Rental_Easy_Functionalities/UpdateUser", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *rental_Easy_FunctionalitiesClient) CreateItem(ctx context.Context, in *Item, opts ...grpc.CallOption) (*Item, error) {
	out := new(Item)
	err := c.cc.Invoke(ctx, "/rentalmgmt.Rental_Easy_Functionalities/CreateItem", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *rental_Easy_FunctionalitiesClient) GetAllItems(ctx context.Context, in *ItemRequest, opts ...grpc.CallOption) (Rental_Easy_Functionalities_GetAllItemsClient, error) {
	stream, err := c.cc.NewStream(ctx, &Rental_Easy_Functionalities_ServiceDesc.Streams[0], "/rentalmgmt.Rental_Easy_Functionalities/GetAllItems", opts...)
	if err != nil {
		return nil, err
	}
	x := &rental_Easy_FunctionalitiesGetAllItemsClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type Rental_Easy_Functionalities_GetAllItemsClient interface {
	Recv() (*Item, error)
	grpc.ClientStream
}

type rental_Easy_FunctionalitiesGetAllItemsClient struct {
	grpc.ClientStream
}

func (x *rental_Easy_FunctionalitiesGetAllItemsClient) Recv() (*Item, error) {
	m := new(Item)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *rental_Easy_FunctionalitiesClient) GetItemById(ctx context.Context, in *Item, opts ...grpc.CallOption) (*Item, error) {
	out := new(Item)
	err := c.cc.Invoke(ctx, "/rentalmgmt.Rental_Easy_Functionalities/GetItemById", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *rental_Easy_FunctionalitiesClient) UpdateItem(ctx context.Context, in *Item, opts ...grpc.CallOption) (*Item, error) {
	out := new(Item)
	err := c.cc.Invoke(ctx, "/rentalmgmt.Rental_Easy_Functionalities/UpdateItem", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *rental_Easy_FunctionalitiesClient) DeleteItem(ctx context.Context, in *Item, opts ...grpc.CallOption) (*Item, error) {
	out := new(Item)
	err := c.cc.Invoke(ctx, "/rentalmgmt.Rental_Easy_Functionalities/DeleteItem", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *rental_Easy_FunctionalitiesClient) GetUserLeasedItems(ctx context.Context, in *User, opts ...grpc.CallOption) (Rental_Easy_Functionalities_GetUserLeasedItemsClient, error) {
	stream, err := c.cc.NewStream(ctx, &Rental_Easy_Functionalities_ServiceDesc.Streams[1], "/rentalmgmt.Rental_Easy_Functionalities/GetUserLeasedItems", opts...)
	if err != nil {
		return nil, err
	}
	x := &rental_Easy_FunctionalitiesGetUserLeasedItemsClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type Rental_Easy_Functionalities_GetUserLeasedItemsClient interface {
	Recv() (*Item, error)
	grpc.ClientStream
}

type rental_Easy_FunctionalitiesGetUserLeasedItemsClient struct {
	grpc.ClientStream
}

func (x *rental_Easy_FunctionalitiesGetUserLeasedItemsClient) Recv() (*Item, error) {
	m := new(Item)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *rental_Easy_FunctionalitiesClient) BookItem(ctx context.Context, in *Booking, opts ...grpc.CallOption) (*Booking, error) {
	out := new(Booking)
	err := c.cc.Invoke(ctx, "/rentalmgmt.Rental_Easy_Functionalities/BookItem", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *rental_Easy_FunctionalitiesClient) GetUserBookedItems(ctx context.Context, in *User, opts ...grpc.CallOption) (Rental_Easy_Functionalities_GetUserBookedItemsClient, error) {
	stream, err := c.cc.NewStream(ctx, &Rental_Easy_Functionalities_ServiceDesc.Streams[2], "/rentalmgmt.Rental_Easy_Functionalities/GetUserBookedItems", opts...)
	if err != nil {
		return nil, err
	}
	x := &rental_Easy_FunctionalitiesGetUserBookedItemsClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type Rental_Easy_Functionalities_GetUserBookedItemsClient interface {
	Recv() (*Booking, error)
	grpc.ClientStream
}

type rental_Easy_FunctionalitiesGetUserBookedItemsClient struct {
	grpc.ClientStream
}

func (x *rental_Easy_FunctionalitiesGetUserBookedItemsClient) Recv() (*Booking, error) {
	m := new(Booking)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *rental_Easy_FunctionalitiesClient) AddReview(ctx context.Context, in *Review, opts ...grpc.CallOption) (*Review, error) {
	out := new(Review)
	err := c.cc.Invoke(ctx, "/rentalmgmt.Rental_Easy_Functionalities/AddReview", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *rental_Easy_FunctionalitiesClient) UpdateReview(ctx context.Context, in *Review, opts ...grpc.CallOption) (*Review, error) {
	out := new(Review)
	err := c.cc.Invoke(ctx, "/rentalmgmt.Rental_Easy_Functionalities/UpdateReview", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *rental_Easy_FunctionalitiesClient) DeleteReview(ctx context.Context, in *Review, opts ...grpc.CallOption) (*Review, error) {
	out := new(Review)
	err := c.cc.Invoke(ctx, "/rentalmgmt.Rental_Easy_Functionalities/DeleteReview", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *rental_Easy_FunctionalitiesClient) GetAllReviews(ctx context.Context, in *Item, opts ...grpc.CallOption) (Rental_Easy_Functionalities_GetAllReviewsClient, error) {
	stream, err := c.cc.NewStream(ctx, &Rental_Easy_Functionalities_ServiceDesc.Streams[3], "/rentalmgmt.Rental_Easy_Functionalities/GetAllReviews", opts...)
	if err != nil {
		return nil, err
	}
	x := &rental_Easy_FunctionalitiesGetAllReviewsClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type Rental_Easy_Functionalities_GetAllReviewsClient interface {
	Recv() (*Review, error)
	grpc.ClientStream
}

type rental_Easy_FunctionalitiesGetAllReviewsClient struct {
	grpc.ClientStream
}

func (x *rental_Easy_FunctionalitiesGetAllReviewsClient) Recv() (*Review, error) {
	m := new(Review)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *rental_Easy_FunctionalitiesClient) SearchItems(ctx context.Context, in *ItemRequest, opts ...grpc.CallOption) (Rental_Easy_Functionalities_SearchItemsClient, error) {
	stream, err := c.cc.NewStream(ctx, &Rental_Easy_Functionalities_ServiceDesc.Streams[4], "/rentalmgmt.Rental_Easy_Functionalities/SearchItems", opts...)
	if err != nil {
		return nil, err
	}
	x := &rental_Easy_FunctionalitiesSearchItemsClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type Rental_Easy_Functionalities_SearchItemsClient interface {
	Recv() (*Item, error)
	grpc.ClientStream
}

type rental_Easy_FunctionalitiesSearchItemsClient struct {
	grpc.ClientStream
}

func (x *rental_Easy_FunctionalitiesSearchItemsClient) Recv() (*Item, error) {
	m := new(Item)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// Rental_Easy_FunctionalitiesServer is the server API for Rental_Easy_Functionalities service.
// All implementations must embed UnimplementedRental_Easy_FunctionalitiesServer
// for forward compatibility
type Rental_Easy_FunctionalitiesServer interface {
	CreateUser(context.Context, *User) (*User, error)
	GetUser(context.Context, *User) (*User, error)
	UpdateUser(context.Context, *User) (*User, error)
	CreateItem(context.Context, *Item) (*Item, error)
	GetAllItems(*ItemRequest, Rental_Easy_Functionalities_GetAllItemsServer) error
	GetItemById(context.Context, *Item) (*Item, error)
	UpdateItem(context.Context, *Item) (*Item, error)
	DeleteItem(context.Context, *Item) (*Item, error)
	GetUserLeasedItems(*User, Rental_Easy_Functionalities_GetUserLeasedItemsServer) error
	BookItem(context.Context, *Booking) (*Booking, error)
	GetUserBookedItems(*User, Rental_Easy_Functionalities_GetUserBookedItemsServer) error
	AddReview(context.Context, *Review) (*Review, error)
	UpdateReview(context.Context, *Review) (*Review, error)
	DeleteReview(context.Context, *Review) (*Review, error)
	GetAllReviews(*Item, Rental_Easy_Functionalities_GetAllReviewsServer) error
	SearchItems(*ItemRequest, Rental_Easy_Functionalities_SearchItemsServer) error
	mustEmbedUnimplementedRental_Easy_FunctionalitiesServer()
}

// UnimplementedRental_Easy_FunctionalitiesServer must be embedded to have forward compatible implementations.
type UnimplementedRental_Easy_FunctionalitiesServer struct {
}

func (UnimplementedRental_Easy_FunctionalitiesServer) CreateUser(context.Context, *User) (*User, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateUser not implemented")
}
func (UnimplementedRental_Easy_FunctionalitiesServer) GetUser(context.Context, *User) (*User, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetUser not implemented")
}
func (UnimplementedRental_Easy_FunctionalitiesServer) UpdateUser(context.Context, *User) (*User, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateUser not implemented")
}
func (UnimplementedRental_Easy_FunctionalitiesServer) CreateItem(context.Context, *Item) (*Item, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateItem not implemented")
}
func (UnimplementedRental_Easy_FunctionalitiesServer) GetAllItems(*ItemRequest, Rental_Easy_Functionalities_GetAllItemsServer) error {
	return status.Errorf(codes.Unimplemented, "method GetAllItems not implemented")
}
func (UnimplementedRental_Easy_FunctionalitiesServer) GetItemById(context.Context, *Item) (*Item, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetItemById not implemented")
}
func (UnimplementedRental_Easy_FunctionalitiesServer) UpdateItem(context.Context, *Item) (*Item, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateItem not implemented")
}
func (UnimplementedRental_Easy_FunctionalitiesServer) DeleteItem(context.Context, *Item) (*Item, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteItem not implemented")
}
func (UnimplementedRental_Easy_FunctionalitiesServer) GetUserLeasedItems(*User, Rental_Easy_Functionalities_GetUserLeasedItemsServer) error {
	return status.Errorf(codes.Unimplemented, "method GetUserLeasedItems not implemented")
}
func (UnimplementedRental_Easy_FunctionalitiesServer) BookItem(context.Context, *Booking) (*Booking, error) {
	return nil, status.Errorf(codes.Unimplemented, "method BookItem not implemented")
}
func (UnimplementedRental_Easy_FunctionalitiesServer) GetUserBookedItems(*User, Rental_Easy_Functionalities_GetUserBookedItemsServer) error {
	return status.Errorf(codes.Unimplemented, "method GetUserBookedItems not implemented")
}
func (UnimplementedRental_Easy_FunctionalitiesServer) AddReview(context.Context, *Review) (*Review, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AddReview not implemented")
}
func (UnimplementedRental_Easy_FunctionalitiesServer) UpdateReview(context.Context, *Review) (*Review, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateReview not implemented")
}
func (UnimplementedRental_Easy_FunctionalitiesServer) DeleteReview(context.Context, *Review) (*Review, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteReview not implemented")
}
func (UnimplementedRental_Easy_FunctionalitiesServer) GetAllReviews(*Item, Rental_Easy_Functionalities_GetAllReviewsServer) error {
	return status.Errorf(codes.Unimplemented, "method GetAllReviews not implemented")
}
func (UnimplementedRental_Easy_FunctionalitiesServer) SearchItems(*ItemRequest, Rental_Easy_Functionalities_SearchItemsServer) error {
	return status.Errorf(codes.Unimplemented, "method SearchItems not implemented")
}
func (UnimplementedRental_Easy_FunctionalitiesServer) mustEmbedUnimplementedRental_Easy_FunctionalitiesServer() {
}

// UnsafeRental_Easy_FunctionalitiesServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to Rental_Easy_FunctionalitiesServer will
// result in compilation errors.
type UnsafeRental_Easy_FunctionalitiesServer interface {
	mustEmbedUnimplementedRental_Easy_FunctionalitiesServer()
}

func RegisterRental_Easy_FunctionalitiesServer(s grpc.ServiceRegistrar, srv Rental_Easy_FunctionalitiesServer) {
	s.RegisterService(&Rental_Easy_Functionalities_ServiceDesc, srv)
}

func _Rental_Easy_Functionalities_CreateUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(User)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(Rental_Easy_FunctionalitiesServer).CreateUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/rentalmgmt.Rental_Easy_Functionalities/CreateUser",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(Rental_Easy_FunctionalitiesServer).CreateUser(ctx, req.(*User))
	}
	return interceptor(ctx, in, info, handler)
}

func _Rental_Easy_Functionalities_GetUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(User)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(Rental_Easy_FunctionalitiesServer).GetUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/rentalmgmt.Rental_Easy_Functionalities/GetUser",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(Rental_Easy_FunctionalitiesServer).GetUser(ctx, req.(*User))
	}
	return interceptor(ctx, in, info, handler)
}

func _Rental_Easy_Functionalities_UpdateUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(User)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(Rental_Easy_FunctionalitiesServer).UpdateUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/rentalmgmt.Rental_Easy_Functionalities/UpdateUser",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(Rental_Easy_FunctionalitiesServer).UpdateUser(ctx, req.(*User))
	}
	return interceptor(ctx, in, info, handler)
}

func _Rental_Easy_Functionalities_CreateItem_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Item)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(Rental_Easy_FunctionalitiesServer).CreateItem(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/rentalmgmt.Rental_Easy_Functionalities/CreateItem",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(Rental_Easy_FunctionalitiesServer).CreateItem(ctx, req.(*Item))
	}
	return interceptor(ctx, in, info, handler)
}

func _Rental_Easy_Functionalities_GetAllItems_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(ItemRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(Rental_Easy_FunctionalitiesServer).GetAllItems(m, &rental_Easy_FunctionalitiesGetAllItemsServer{stream})
}

type Rental_Easy_Functionalities_GetAllItemsServer interface {
	Send(*Item) error
	grpc.ServerStream
}

type rental_Easy_FunctionalitiesGetAllItemsServer struct {
	grpc.ServerStream
}

func (x *rental_Easy_FunctionalitiesGetAllItemsServer) Send(m *Item) error {
	return x.ServerStream.SendMsg(m)
}

func _Rental_Easy_Functionalities_GetItemById_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Item)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(Rental_Easy_FunctionalitiesServer).GetItemById(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/rentalmgmt.Rental_Easy_Functionalities/GetItemById",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(Rental_Easy_FunctionalitiesServer).GetItemById(ctx, req.(*Item))
	}
	return interceptor(ctx, in, info, handler)
}

func _Rental_Easy_Functionalities_UpdateItem_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Item)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(Rental_Easy_FunctionalitiesServer).UpdateItem(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/rentalmgmt.Rental_Easy_Functionalities/UpdateItem",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(Rental_Easy_FunctionalitiesServer).UpdateItem(ctx, req.(*Item))
	}
	return interceptor(ctx, in, info, handler)
}

func _Rental_Easy_Functionalities_DeleteItem_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Item)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(Rental_Easy_FunctionalitiesServer).DeleteItem(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/rentalmgmt.Rental_Easy_Functionalities/DeleteItem",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(Rental_Easy_FunctionalitiesServer).DeleteItem(ctx, req.(*Item))
	}
	return interceptor(ctx, in, info, handler)
}

func _Rental_Easy_Functionalities_GetUserLeasedItems_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(User)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(Rental_Easy_FunctionalitiesServer).GetUserLeasedItems(m, &rental_Easy_FunctionalitiesGetUserLeasedItemsServer{stream})
}

type Rental_Easy_Functionalities_GetUserLeasedItemsServer interface {
	Send(*Item) error
	grpc.ServerStream
}

type rental_Easy_FunctionalitiesGetUserLeasedItemsServer struct {
	grpc.ServerStream
}

func (x *rental_Easy_FunctionalitiesGetUserLeasedItemsServer) Send(m *Item) error {
	return x.ServerStream.SendMsg(m)
}

func _Rental_Easy_Functionalities_BookItem_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Booking)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(Rental_Easy_FunctionalitiesServer).BookItem(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/rentalmgmt.Rental_Easy_Functionalities/BookItem",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(Rental_Easy_FunctionalitiesServer).BookItem(ctx, req.(*Booking))
	}
	return interceptor(ctx, in, info, handler)
}

func _Rental_Easy_Functionalities_GetUserBookedItems_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(User)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(Rental_Easy_FunctionalitiesServer).GetUserBookedItems(m, &rental_Easy_FunctionalitiesGetUserBookedItemsServer{stream})
}

type Rental_Easy_Functionalities_GetUserBookedItemsServer interface {
	Send(*Booking) error
	grpc.ServerStream
}

type rental_Easy_FunctionalitiesGetUserBookedItemsServer struct {
	grpc.ServerStream
}

func (x *rental_Easy_FunctionalitiesGetUserBookedItemsServer) Send(m *Booking) error {
	return x.ServerStream.SendMsg(m)
}

func _Rental_Easy_Functionalities_AddReview_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Review)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(Rental_Easy_FunctionalitiesServer).AddReview(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/rentalmgmt.Rental_Easy_Functionalities/AddReview",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(Rental_Easy_FunctionalitiesServer).AddReview(ctx, req.(*Review))
	}
	return interceptor(ctx, in, info, handler)
}

func _Rental_Easy_Functionalities_UpdateReview_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Review)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(Rental_Easy_FunctionalitiesServer).UpdateReview(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/rentalmgmt.Rental_Easy_Functionalities/UpdateReview",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(Rental_Easy_FunctionalitiesServer).UpdateReview(ctx, req.(*Review))
	}
	return interceptor(ctx, in, info, handler)
}

func _Rental_Easy_Functionalities_DeleteReview_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Review)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(Rental_Easy_FunctionalitiesServer).DeleteReview(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/rentalmgmt.Rental_Easy_Functionalities/DeleteReview",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(Rental_Easy_FunctionalitiesServer).DeleteReview(ctx, req.(*Review))
	}
	return interceptor(ctx, in, info, handler)
}

func _Rental_Easy_Functionalities_GetAllReviews_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(Item)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(Rental_Easy_FunctionalitiesServer).GetAllReviews(m, &rental_Easy_FunctionalitiesGetAllReviewsServer{stream})
}

type Rental_Easy_Functionalities_GetAllReviewsServer interface {
	Send(*Review) error
	grpc.ServerStream
}

type rental_Easy_FunctionalitiesGetAllReviewsServer struct {
	grpc.ServerStream
}

func (x *rental_Easy_FunctionalitiesGetAllReviewsServer) Send(m *Review) error {
	return x.ServerStream.SendMsg(m)
}

func _Rental_Easy_Functionalities_SearchItems_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(ItemRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(Rental_Easy_FunctionalitiesServer).SearchItems(m, &rental_Easy_FunctionalitiesSearchItemsServer{stream})
}

type Rental_Easy_Functionalities_SearchItemsServer interface {
	Send(*Item) error
	grpc.ServerStream
}

type rental_Easy_FunctionalitiesSearchItemsServer struct {
	grpc.ServerStream
}

func (x *rental_Easy_FunctionalitiesSearchItemsServer) Send(m *Item) error {
	return x.ServerStream.SendMsg(m)
}

// Rental_Easy_Functionalities_ServiceDesc is the grpc.ServiceDesc for Rental_Easy_Functionalities service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Rental_Easy_Functionalities_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "rentalmgmt.Rental_Easy_Functionalities",
	HandlerType: (*Rental_Easy_FunctionalitiesServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateUser",
			Handler:    _Rental_Easy_Functionalities_CreateUser_Handler,
		},
		{
			MethodName: "GetUser",
			Handler:    _Rental_Easy_Functionalities_GetUser_Handler,
		},
		{
			MethodName: "UpdateUser",
			Handler:    _Rental_Easy_Functionalities_UpdateUser_Handler,
		},
		{
			MethodName: "CreateItem",
			Handler:    _Rental_Easy_Functionalities_CreateItem_Handler,
		},
		{
			MethodName: "GetItemById",
			Handler:    _Rental_Easy_Functionalities_GetItemById_Handler,
		},
		{
			MethodName: "UpdateItem",
			Handler:    _Rental_Easy_Functionalities_UpdateItem_Handler,
		},
		{
			MethodName: "DeleteItem",
			Handler:    _Rental_Easy_Functionalities_DeleteItem_Handler,
		},
		{
			MethodName: "BookItem",
			Handler:    _Rental_Easy_Functionalities_BookItem_Handler,
		},
		{
			MethodName: "AddReview",
			Handler:    _Rental_Easy_Functionalities_AddReview_Handler,
		},
		{
			MethodName: "UpdateReview",
			Handler:    _Rental_Easy_Functionalities_UpdateReview_Handler,
		},
		{
			MethodName: "DeleteReview",
			Handler:    _Rental_Easy_Functionalities_DeleteReview_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "GetAllItems",
			Handler:       _Rental_Easy_Functionalities_GetAllItems_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "GetUserLeasedItems",
			Handler:       _Rental_Easy_Functionalities_GetUserLeasedItems_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "GetUserBookedItems",
			Handler:       _Rental_Easy_Functionalities_GetUserBookedItems_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "GetAllReviews",
			Handler:       _Rental_Easy_Functionalities_GetAllReviews_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "SearchItems",
			Handler:       _Rental_Easy_Functionalities_SearchItems_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "pkg/rentalmgmt/rentalmgmt.proto",
}
