// Code generated by protoc-gen-go. DO NOT EDIT.
// source: pkg/rentalmgmt/rentalmgmt.proto

package rentalmgmt

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type ItemRequest_Category int32

const (
	ItemRequest_MobilePhones ItemRequest_Category = 0
	ItemRequest_Laptops      ItemRequest_Category = 1
	ItemRequest_Accessories  ItemRequest_Category = 2
)

var ItemRequest_Category_name = map[int32]string{
	0: "MobilePhones",
	1: "Laptops",
	2: "Accessories",
}

var ItemRequest_Category_value = map[string]int32{
	"MobilePhones": 0,
	"Laptops":      1,
	"Accessories":  2,
}

func (x ItemRequest_Category) String() string {
	return proto.EnumName(ItemRequest_Category_name, int32(x))
}

func (ItemRequest_Category) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_3231b20ba83710a0, []int{2, 0}
}

//USER'S SIDE
//Create New User
type User struct {
	Id                   int32    `protobuf:"varint,1,opt,name=Id,proto3" json:"Id,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=Name,proto3" json:"Name,omitempty"`
	Email                string   `protobuf:"bytes,3,opt,name=Email,proto3" json:"Email,omitempty"`
	PhoneNumber          string   `protobuf:"bytes,4,opt,name=PhoneNumber,proto3" json:"PhoneNumber,omitempty"`
	Address              string   `protobuf:"bytes,5,opt,name=Address,proto3" json:"Address,omitempty"`
	District             string   `protobuf:"bytes,6,opt,name=District,proto3" json:"District,omitempty"`
	PostalCode           string   `protobuf:"bytes,7,opt,name=PostalCode,proto3" json:"PostalCode,omitempty"`
	Country              string   `protobuf:"bytes,8,opt,name=Country,proto3" json:"Country,omitempty"`
	Status               string   `protobuf:"bytes,9,opt,name=Status,proto3" json:"Status,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *User) Reset()         { *m = User{} }
func (m *User) String() string { return proto.CompactTextString(m) }
func (*User) ProtoMessage()    {}
func (*User) Descriptor() ([]byte, []int) {
	return fileDescriptor_3231b20ba83710a0, []int{0}
}

func (m *User) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_User.Unmarshal(m, b)
}
func (m *User) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_User.Marshal(b, m, deterministic)
}
func (m *User) XXX_Merge(src proto.Message) {
	xxx_messageInfo_User.Merge(m, src)
}
func (m *User) XXX_Size() int {
	return xxx_messageInfo_User.Size(m)
}
func (m *User) XXX_DiscardUnknown() {
	xxx_messageInfo_User.DiscardUnknown(m)
}

var xxx_messageInfo_User proto.InternalMessageInfo

func (m *User) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *User) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *User) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *User) GetPhoneNumber() string {
	if m != nil {
		return m.PhoneNumber
	}
	return ""
}

func (m *User) GetAddress() string {
	if m != nil {
		return m.Address
	}
	return ""
}

func (m *User) GetDistrict() string {
	if m != nil {
		return m.District
	}
	return ""
}

func (m *User) GetPostalCode() string {
	if m != nil {
		return m.PostalCode
	}
	return ""
}

func (m *User) GetCountry() string {
	if m != nil {
		return m.Country
	}
	return ""
}

func (m *User) GetStatus() string {
	if m != nil {
		return m.Status
	}
	return ""
}

//Get a Particular Item with all Details
type Item struct {
	Id                   int32    `protobuf:"varint,1,opt,name=Id,proto3" json:"Id,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=Name,proto3" json:"Name,omitempty"`
	Description          string   `protobuf:"bytes,3,opt,name=Description,proto3" json:"Description,omitempty"`
	Category             string   `protobuf:"bytes,4,opt,name=Category,proto3" json:"Category,omitempty"`
	AvailableFrom        string   `protobuf:"bytes,5,opt,name=AvailableFrom,proto3" json:"AvailableFrom,omitempty"`
	AvailableTo          string   `protobuf:"bytes,6,opt,name=AvailableTo,proto3" json:"AvailableTo,omitempty"`
	AmountPerDay         int32    `protobuf:"varint,7,opt,name=AmountPerDay,proto3" json:"AmountPerDay,omitempty"`
	UserId               int32    `protobuf:"varint,8,opt,name=UserId,proto3" json:"UserId,omitempty"`
	Status               string   `protobuf:"bytes,9,opt,name=Status,proto3" json:"Status,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Item) Reset()         { *m = Item{} }
func (m *Item) String() string { return proto.CompactTextString(m) }
func (*Item) ProtoMessage()    {}
func (*Item) Descriptor() ([]byte, []int) {
	return fileDescriptor_3231b20ba83710a0, []int{1}
}

func (m *Item) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Item.Unmarshal(m, b)
}
func (m *Item) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Item.Marshal(b, m, deterministic)
}
func (m *Item) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Item.Merge(m, src)
}
func (m *Item) XXX_Size() int {
	return xxx_messageInfo_Item.Size(m)
}
func (m *Item) XXX_DiscardUnknown() {
	xxx_messageInfo_Item.DiscardUnknown(m)
}

var xxx_messageInfo_Item proto.InternalMessageInfo

func (m *Item) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *Item) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Item) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

func (m *Item) GetCategory() string {
	if m != nil {
		return m.Category
	}
	return ""
}

func (m *Item) GetAvailableFrom() string {
	if m != nil {
		return m.AvailableFrom
	}
	return ""
}

func (m *Item) GetAvailableTo() string {
	if m != nil {
		return m.AvailableTo
	}
	return ""
}

func (m *Item) GetAmountPerDay() int32 {
	if m != nil {
		return m.AmountPerDay
	}
	return 0
}

func (m *Item) GetUserId() int32 {
	if m != nil {
		return m.UserId
	}
	return 0
}

func (m *Item) GetStatus() string {
	if m != nil {
		return m.Status
	}
	return ""
}

//REQUEST AND RESPONSE
//For Requesting
type ItemRequest struct {
	Request              string               `protobuf:"bytes,1,opt,name=Request,proto3" json:"Request,omitempty"`
	Category             ItemRequest_Category `protobuf:"varint,2,opt,name=category,proto3,enum=rentalmgmt.ItemRequest_Category" json:"category,omitempty"`
	Status               string               `protobuf:"bytes,3,opt,name=Status,proto3" json:"Status,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *ItemRequest) Reset()         { *m = ItemRequest{} }
func (m *ItemRequest) String() string { return proto.CompactTextString(m) }
func (*ItemRequest) ProtoMessage()    {}
func (*ItemRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_3231b20ba83710a0, []int{2}
}

func (m *ItemRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ItemRequest.Unmarshal(m, b)
}
func (m *ItemRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ItemRequest.Marshal(b, m, deterministic)
}
func (m *ItemRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ItemRequest.Merge(m, src)
}
func (m *ItemRequest) XXX_Size() int {
	return xxx_messageInfo_ItemRequest.Size(m)
}
func (m *ItemRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ItemRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ItemRequest proto.InternalMessageInfo

func (m *ItemRequest) GetRequest() string {
	if m != nil {
		return m.Request
	}
	return ""
}

func (m *ItemRequest) GetCategory() ItemRequest_Category {
	if m != nil {
		return m.Category
	}
	return ItemRequest_MobilePhones
}

func (m *ItemRequest) GetStatus() string {
	if m != nil {
		return m.Status
	}
	return ""
}

//BOOKING RELATED
//To Show the Booked Items
type Booking struct {
	Id                   int32    `protobuf:"varint,1,opt,name=Id,proto3" json:"Id,omitempty"`
	ItemName             string   `protobuf:"bytes,2,opt,name=ItemName,proto3" json:"ItemName,omitempty"`
	StartDate            string   `protobuf:"bytes,3,opt,name=StartDate,proto3" json:"StartDate,omitempty"`
	EndDate              string   `protobuf:"bytes,4,opt,name=EndDate,proto3" json:"EndDate,omitempty"`
	TotalAmount          int32    `protobuf:"varint,5,opt,name=TotalAmount,proto3" json:"TotalAmount,omitempty"`
	UserId               int32    `protobuf:"varint,6,opt,name=UserId,proto3" json:"UserId,omitempty"`
	ItemId               int32    `protobuf:"varint,7,opt,name=ItemId,proto3" json:"ItemId,omitempty"`
	Status               string   `protobuf:"bytes,8,opt,name=Status,proto3" json:"Status,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Booking) Reset()         { *m = Booking{} }
func (m *Booking) String() string { return proto.CompactTextString(m) }
func (*Booking) ProtoMessage()    {}
func (*Booking) Descriptor() ([]byte, []int) {
	return fileDescriptor_3231b20ba83710a0, []int{3}
}

func (m *Booking) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Booking.Unmarshal(m, b)
}
func (m *Booking) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Booking.Marshal(b, m, deterministic)
}
func (m *Booking) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Booking.Merge(m, src)
}
func (m *Booking) XXX_Size() int {
	return xxx_messageInfo_Booking.Size(m)
}
func (m *Booking) XXX_DiscardUnknown() {
	xxx_messageInfo_Booking.DiscardUnknown(m)
}

var xxx_messageInfo_Booking proto.InternalMessageInfo

func (m *Booking) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *Booking) GetItemName() string {
	if m != nil {
		return m.ItemName
	}
	return ""
}

func (m *Booking) GetStartDate() string {
	if m != nil {
		return m.StartDate
	}
	return ""
}

func (m *Booking) GetEndDate() string {
	if m != nil {
		return m.EndDate
	}
	return ""
}

func (m *Booking) GetTotalAmount() int32 {
	if m != nil {
		return m.TotalAmount
	}
	return 0
}

func (m *Booking) GetUserId() int32 {
	if m != nil {
		return m.UserId
	}
	return 0
}

func (m *Booking) GetItemId() int32 {
	if m != nil {
		return m.ItemId
	}
	return 0
}

func (m *Booking) GetStatus() string {
	if m != nil {
		return m.Status
	}
	return ""
}

type Review struct {
	Id                   int32    `protobuf:"varint,1,opt,name=Id,proto3" json:"Id,omitempty"`
	Comment              string   `protobuf:"bytes,2,opt,name=Comment,proto3" json:"Comment,omitempty"`
	Rating               int32    `protobuf:"varint,3,opt,name=Rating,proto3" json:"Rating,omitempty"`
	UserId               int32    `protobuf:"varint,4,opt,name=UserId,proto3" json:"UserId,omitempty"`
	ItemId               int32    `protobuf:"varint,5,opt,name=ItemId,proto3" json:"ItemId,omitempty"`
	Status               string   `protobuf:"bytes,6,opt,name=Status,proto3" json:"Status,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Review) Reset()         { *m = Review{} }
func (m *Review) String() string { return proto.CompactTextString(m) }
func (*Review) ProtoMessage()    {}
func (*Review) Descriptor() ([]byte, []int) {
	return fileDescriptor_3231b20ba83710a0, []int{4}
}

func (m *Review) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Review.Unmarshal(m, b)
}
func (m *Review) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Review.Marshal(b, m, deterministic)
}
func (m *Review) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Review.Merge(m, src)
}
func (m *Review) XXX_Size() int {
	return xxx_messageInfo_Review.Size(m)
}
func (m *Review) XXX_DiscardUnknown() {
	xxx_messageInfo_Review.DiscardUnknown(m)
}

var xxx_messageInfo_Review proto.InternalMessageInfo

func (m *Review) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *Review) GetComment() string {
	if m != nil {
		return m.Comment
	}
	return ""
}

func (m *Review) GetRating() int32 {
	if m != nil {
		return m.Rating
	}
	return 0
}

func (m *Review) GetUserId() int32 {
	if m != nil {
		return m.UserId
	}
	return 0
}

func (m *Review) GetItemId() int32 {
	if m != nil {
		return m.ItemId
	}
	return 0
}

func (m *Review) GetStatus() string {
	if m != nil {
		return m.Status
	}
	return ""
}

func init() {
	proto.RegisterEnum("rentalmgmt.ItemRequest_Category", ItemRequest_Category_name, ItemRequest_Category_value)
	proto.RegisterType((*User)(nil), "rentalmgmt.User")
	proto.RegisterType((*Item)(nil), "rentalmgmt.Item")
	proto.RegisterType((*ItemRequest)(nil), "rentalmgmt.ItemRequest")
	proto.RegisterType((*Booking)(nil), "rentalmgmt.Booking")
	proto.RegisterType((*Review)(nil), "rentalmgmt.Review")
}

func init() { proto.RegisterFile("pkg/rentalmgmt/rentalmgmt.proto", fileDescriptor_3231b20ba83710a0) }

var fileDescriptor_3231b20ba83710a0 = []byte{
	// 747 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x9c, 0x55, 0xdd, 0x4e, 0x1a, 0x41,
	0x14, 0x66, 0x91, 0xe5, 0xe7, 0xa0, 0x96, 0x4c, 0x9b, 0x76, 0x83, 0xfd, 0x21, 0x9b, 0x5e, 0x78,
	0x85, 0x06, 0xd3, 0xa6, 0x6d, 0x4c, 0x1a, 0x04, 0x35, 0x24, 0xd6, 0x98, 0x55, 0x6f, 0x7a, 0x63,
	0x06, 0xf6, 0x04, 0x37, 0xee, 0xee, 0xd0, 0x9d, 0xc1, 0x86, 0xfb, 0x3e, 0x41, 0x9f, 0xa0, 0xaf,
	0xd1, 0x27, 0xe9, 0x3b, 0xf4, 0x29, 0x9a, 0x99, 0x1d, 0xd6, 0x41, 0x20, 0x15, 0xef, 0xe6, 0xfb,
	0x0e, 0x67, 0xce, 0xf9, 0xbe, 0x73, 0x86, 0x85, 0x37, 0xa3, 0x9b, 0xe1, 0x4e, 0x82, 0xb1, 0xa0,
	0x61, 0x34, 0x8c, 0x84, 0x71, 0x6c, 0x8e, 0x12, 0x26, 0x18, 0x81, 0x3b, 0xc6, 0xfd, 0x6b, 0x41,
	0xe1, 0x92, 0x63, 0x42, 0x36, 0x21, 0xdf, 0xf3, 0x1d, 0xab, 0x61, 0x6d, 0xdb, 0x5e, 0xbe, 0xe7,
	0x13, 0x02, 0x85, 0x53, 0x1a, 0xa1, 0x93, 0x6f, 0x58, 0xdb, 0x15, 0x4f, 0x9d, 0xc9, 0x33, 0xb0,
	0x0f, 0x23, 0x1a, 0x84, 0xce, 0x9a, 0x22, 0x53, 0x40, 0x1a, 0x50, 0x3d, 0xbb, 0x66, 0x31, 0x9e,
	0x8e, 0xa3, 0x3e, 0x26, 0x4e, 0x41, 0xc5, 0x4c, 0x8a, 0x38, 0x50, 0x6a, 0xfb, 0x7e, 0x82, 0x9c,
	0x3b, 0xb6, 0x8a, 0x4e, 0x21, 0xa9, 0x43, 0xb9, 0x1b, 0x70, 0x91, 0x04, 0x03, 0xe1, 0x14, 0x55,
	0x28, 0xc3, 0xe4, 0x35, 0xc0, 0x19, 0xe3, 0x82, 0x86, 0x1d, 0xe6, 0xa3, 0x53, 0x52, 0x51, 0x83,
	0x91, 0xb7, 0x76, 0xd8, 0x38, 0x16, 0xc9, 0xc4, 0x29, 0xa7, 0xb7, 0x6a, 0x48, 0x9e, 0x43, 0xf1,
	0x5c, 0x50, 0x31, 0xe6, 0x4e, 0x45, 0x05, 0x34, 0x72, 0x7f, 0xe4, 0xa1, 0xd0, 0x13, 0x18, 0x3d,
	0x48, 0x6c, 0x03, 0xaa, 0x5d, 0xe4, 0x83, 0x24, 0x18, 0x89, 0x80, 0xc5, 0x5a, 0xb2, 0x49, 0xc9,
	0xe6, 0x3b, 0x54, 0xe0, 0x90, 0x25, 0x13, 0xad, 0x3a, 0xc3, 0xe4, 0x2d, 0x6c, 0xb4, 0x6f, 0x69,
	0x10, 0xd2, 0x7e, 0x88, 0x47, 0x09, 0x8b, 0xb4, 0xf0, 0x59, 0x52, 0xd6, 0xc8, 0x88, 0x0b, 0xa6,
	0x1d, 0x30, 0x29, 0xe2, 0xc2, 0x7a, 0x3b, 0x92, 0xb2, 0xce, 0x30, 0xe9, 0xd2, 0x89, 0xb2, 0xc1,
	0xf6, 0x66, 0x38, 0x29, 0x57, 0x8e, 0xb0, 0xe7, 0x2b, 0x1f, 0x6c, 0x4f, 0xa3, 0xa5, 0x36, 0xfc,
	0xb6, 0xa0, 0x2a, 0x6d, 0xf0, 0xf0, 0xdb, 0x18, 0xb9, 0x90, 0x46, 0xea, 0xa3, 0xb2, 0xa4, 0xe2,
	0x4d, 0x21, 0xd9, 0x87, 0xf2, 0x60, 0xaa, 0x50, 0x7a, 0xb3, 0xd9, 0x6a, 0x34, 0x8d, 0x75, 0x32,
	0x2e, 0x69, 0x4e, 0x95, 0x7b, 0x59, 0x86, 0x51, 0x7f, 0x6d, 0xa6, 0xfe, 0xa7, 0x3b, 0xdf, 0x48,
	0x0d, 0xd6, 0xbf, 0xb0, 0x7e, 0x10, 0xa2, 0xda, 0x17, 0x5e, 0xcb, 0x91, 0x2a, 0x94, 0x4e, 0xe8,
	0x48, 0xb0, 0x11, 0xaf, 0x59, 0xe4, 0x09, 0x54, 0xdb, 0x83, 0x01, 0x72, 0xce, 0x92, 0x00, 0x79,
	0x2d, 0xef, 0xfe, 0xb1, 0xa0, 0x74, 0xc0, 0xd8, 0x4d, 0x10, 0x0f, 0xe7, 0xa6, 0x58, 0x87, 0xb2,
	0xec, 0xc8, 0x98, 0x64, 0x86, 0xc9, 0x4b, 0xa8, 0x9c, 0x0b, 0x9a, 0x88, 0x2e, 0x15, 0xa8, 0xdb,
	0xb9, 0x23, 0xa4, 0x03, 0x87, 0xb1, 0xaf, 0x62, 0xe9, 0x20, 0xa7, 0x50, 0x4e, 0xe8, 0x82, 0x09,
	0x1a, 0xa6, 0x86, 0xab, 0x29, 0xda, 0x9e, 0x49, 0x19, 0xee, 0x17, 0xef, 0xbb, 0x2f, 0xab, 0xf7,
	0x7c, 0x3d, 0x33, 0x8d, 0x0c, 0x57, 0xca, 0x33, 0xae, 0xfc, 0xb4, 0xa0, 0xe8, 0xe1, 0x6d, 0x80,
	0xdf, 0xe7, 0x84, 0xa9, 0x4d, 0x8f, 0x22, 0x8c, 0x85, 0xd6, 0x35, 0x85, 0xf2, 0x32, 0x8f, 0x8a,
	0x20, 0x1e, 0x2a, 0x4d, 0xb6, 0xa7, 0x91, 0xd1, 0x54, 0x61, 0x49, 0x53, 0xf6, 0x92, 0xa6, 0x8a,
	0x66, 0x53, 0xad, 0x5f, 0x25, 0xd8, 0xf2, 0xd4, 0xc0, 0xaf, 0x0e, 0x29, 0x9f, 0x5c, 0x1d, 0x8d,
	0xe3, 0x81, 0xdc, 0x7d, 0x1a, 0x06, 0x22, 0x40, 0x4e, 0x5a, 0x00, 0x9d, 0x04, 0xa9, 0x40, 0xf5,
	0x1f, 0x52, 0x33, 0x97, 0x43, 0x32, 0xf5, 0x39, 0xc6, 0xcd, 0x91, 0x1d, 0x28, 0x1d, 0xa3, 0x58,
	0x21, 0xa1, 0x05, 0x70, 0x39, 0xf2, 0x57, 0x2b, 0x92, 0x35, 0xa6, 0xde, 0x7b, 0xed, 0xfe, 0xd6,
	0xd6, 0xe7, 0x18, 0x37, 0x47, 0xf6, 0xa1, 0x7a, 0x8c, 0xa2, 0x1d, 0x86, 0x12, 0x73, 0xf2, 0x62,
	0xc9, 0xaa, 0x2f, 0xca, 0xdd, 0xb5, 0xc8, 0x9e, 0xca, 0x96, 0xf0, 0x60, 0xd2, 0xf3, 0x1f, 0x58,
	0x32, 0x93, 0xb6, 0x42, 0x9b, 0x2d, 0x80, 0x2e, 0x86, 0xb8, 0xa2, 0x34, 0xa2, 0x3d, 0x3f, 0x41,
	0xca, 0xd1, 0x4f, 0x15, 0xfe, 0xc7, 0xca, 0x4c, 0xda, 0x7b, 0x28, 0xcb, 0x37, 0xa7, 0xea, 0x3d,
	0x35, 0x7f, 0xa1, 0x5f, 0x62, 0x7d, 0x11, 0xe9, 0xe6, 0xc8, 0xe7, 0xac, 0xaa, 0xe4, 0x96, 0x57,
	0x5d, 0x9c, 0xbe, 0x6b, 0x91, 0x77, 0x50, 0x69, 0xfb, 0xbe, 0x7e, 0x15, 0xc4, 0xfc, 0x55, 0xca,
	0xd5, 0x17, 0x70, 0x6e, 0x8e, 0x7c, 0x80, 0xf5, 0xd4, 0xd5, 0xc7, 0x64, 0xa6, 0xde, 0xae, 0x9c,
	0xf9, 0x11, 0x36, 0xd2, 0xe5, 0x49, 0x19, 0xbe, 0x60, 0x30, 0x0b, 0x13, 0x77, 0x2d, 0xb9, 0x77,
	0xe7, 0x48, 0x93, 0xc1, 0xf5, 0x63, 0xf6, 0xee, 0xe0, 0xd5, 0xd7, 0xad, 0x94, 0xbe, 0x42, 0xca,
	0x27, 0xcd, 0x20, 0xde, 0x89, 0x8c, 0x4f, 0x7e, 0xbf, 0xa8, 0xbe, 0xf9, 0x7b, 0xff, 0x02, 0x00,
	0x00, 0xff, 0xff, 0xf3, 0x05, 0x3d, 0x2a, 0x16, 0x08, 0x00, 0x00,
}
